### ISSUE TITLE
interactive-carousel

### ISSUE THREAD

**Issue by ionStici** [ionStici/slider#1]
[interactive-carousel repository](https://github.com/ionStici/interactive-carousel)

## Tasks

- [x] Ensure the Repository Name corresponds 
- [x] Write a concise description and Specify related "Topics"
- [x] Indicate the website link
- [x] Setup tags and releases

**Comment by ionStici** [comment]
## Tools

- [x] Set up `npm`, `vite`, `ESLint`, `gh-pages`
- [x] Ignore unnecessary directories and files with `.gitignore`

**Comment by ionStici** [comment]
## Testing

- [x] Cross Browser Testing
- [x] Test the app in Lighthouse
- [x] The Front-End Checklist
- [x] W3C Validator

**Comment by ionStici** [comment]
## Formals

- [x] Update README accordingly
- [x] Add MIT License
- [x] Add CONTRIBUTING.md

**Comment by ionStici** [comment]
## Code Review

- [x] Refactor source code
- [x] Optimize images
- [x] HTML
- [x] CSS
- [x] JavaScript

**Comment by ionStici** [comment]
- [x] Add '404' page
- [x] Add `robots.txt` file
